[project]
name = "linuxhandcontroller"
version = "0.2.0"
description = "Control Linux volume and brightness with hand gestures"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mediapipe>=0.10.31",
    "opencv-python>=4.12.0.88",
    "numpy>=1.26.0",
    "pulsectl>=24.12.0",
]
